name: restaurant_review_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.7
  path: ^1.8.3
  image_picker: ^0.8.7 # Para selecionar ou tirar fotos
  intl: ^0.18.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/reviews_icon.png
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/Pacifico.ttf
